FROM node:22-alpine AS builder

WORKDIR /app

COPY ./frontend .

RUN npm install & npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

# (Optional) Copy nginx.conf if needed
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
